### ISSUE TITLE
🐞 FilePond's dropzone gets cut off at the bottom

### ISSUE THREAD

**Issue by citrika** [ClassicPress/ClassicPress#1751]
### Expected behavior

When uploading a file, the dropzone's dashed outline should remain as a rectangle.

### Current behavior

In Chromium:

![Image](https://github.com/user-attachments/assets/e4b83923-1034-495c-ba38-a1bace23cc50)

In Firefox:

![Image](https://github.com/user-attachments/assets/20ce4b47-2f86-43c0-aff5-9beb188105fe)

### Possible solution

There might be a more elegant fix than this:
```css
.filepond--panel-bottom.filepond--panel-root {
	transform: unset !important;
}
```

### Steps to reproduce bug

1. Go to Media Library's grid mode.
2. Upload a file.

### ClassicPress version

2.3.1

### PHP version

8.1

### Can you help?

Yes, I will submit a PR
